services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL
    profiles:
      - migrate

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL
    ports:
      - '3000:3000'

volumes:
  sqlite_data:
