services:
  migrate:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.prisma
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL
    profiles:
      - migrate

  app:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

# 查看真实路径：docker volume inspect maxzhangsite_sqlite_data
volumes:
  sqlite_data:
