/**
 * 构建期 MDX 预编译脚本
 *
 * 把 articles/{locale}/*.mdx 编译为 React 组件（TSX 模块），
 * 并生成懒加载清单 manifest.ts。Vite 直接打包生成的 TSX，
 * 不依赖 @mdx-js/rollup 在 TanStack Start SSR 环境中的 transform。
 *
 * 用法：
 *   node scripts/generate-mdx.mjs          # 全量生成
 *   node scripts/generate-mdx.mjs --watch  # 监听文章变更（开发模式）
 */

/* global process, console */

import { compile } from '@mdx-js/mdx'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import remarkFrontmatter from 'remark-frontmatter'
import remarkGfm from 'remark-gfm'
import rehypePrettyCode from 'rehype-pretty-code'
import { bundledThemes } from 'shiki/themes'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const articlesDir = path.join(root, 'articles')
const outDir = path.join(root, 'src', 'features', 'posts', 'generated')
const watch = process.argv.includes('--watch')

const remarkPlugins = [remarkFrontmatter, remarkGfm]

// Shiki 4 默认包不含 Xcode 主题，采用同风格的 VS Code Light+/Dark+ 双主题
const lightTheme = (await bundledThemes['light-plus']()).default
const darkTheme = (await bundledThemes['dark-plus']()).default

const rehypePlugins = [[rehypePrettyCode, { theme: { light: lightTheme, dark: darkTheme }, keepBackground: false }]]

async function compileMdx(filePath) {
  const source = fs.readFileSync(filePath, 'utf8')
  const code = String(
    await compile(source, {
      jsx: true,
      remarkPlugins,
      rehypePlugins,
    }),
  )
  return code
}

async function generate() {
  const entries = []

  // 仓库可能暂时没有文章（删除全部文章后目录不会进入 Git），
  // 统一补齐目录，让构建在零文章时也能生成空 manifest。
  fs.mkdirSync(articlesDir, { recursive: true })
  fs.mkdirSync(outDir, { recursive: true })

  for (const locale of fs.readdirSync(articlesDir)) {
    const localeDir = path.join(articlesDir, locale)
    if (!fs.statSync(localeDir).isDirectory()) continue

    const localeOut = path.join(outDir, locale)
    fs.mkdirSync(localeOut, { recursive: true })

    for (const file of fs.readdirSync(localeDir).filter((name) => name.endsWith('.mdx'))) {
      const slug = file.replace(/\.mdx$/, '')
      const code = await compileMdx(path.join(localeDir, file))
      const target = path.join(localeOut, `${slug}.tsx`)
      fs.writeFileSync(
        target,
        `// @ts-nocheck\n/* eslint-disable */\n// GENERATED by scripts/generate-mdx.mjs — do not edit\n${code}`,
      )
      entries.push({ locale, slug })
    }
  }

  const manifest = `/* eslint-disable */\n// GENERATED by scripts/generate-mdx.mjs — do not edit\nimport type { MdxModule } from '../mdx-types'\n\nexport const mdxModules: Record<string, () => Promise<MdxModule>> = {\n${entries
    .map(({ locale, slug }) => `  '${locale}/${slug}': () => import('./${locale}/${slug}'),`)
    .join('\n')}\n}\n`
  fs.writeFileSync(path.join(outDir, 'manifest.ts'), manifest)

  console.log(`[generate-mdx] ${entries.length} articles compiled → ${path.relative(root, outDir)}`)
}

if (watch) {
  generate()
  fs.watch(articlesDir, { recursive: true }, () => generate())
  console.log('[generate-mdx] watching articles/ ...')
} else {
  generate()
}
