/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnRouteRouteImport } from './routes/_en/route'
import { Route as ZhRouteRouteImport } from './routes/zh/route'
import { Route as EnIndexRouteImport } from './routes/_en/index'
import { Route as EnAboutRouteImport } from './routes/_en/about'
import { Route as EnChatRouteImport } from './routes/_en/chat'
import { Route as EnPostsRouteRouteImport } from './routes/_en/posts/route'
import { Route as EnSearchRouteImport } from './routes/_en/search'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ZhAboutRouteImport } from './routes/zh/about'
import { Route as ZhChatRouteImport } from './routes/zh/chat'
import { Route as ZhPostsRouteRouteImport } from './routes/zh/posts/route'
import { Route as ZhSearchRouteImport } from './routes/zh/search'
import { Route as EnPostsIndexRouteImport } from './routes/_en/posts/index'
import { Route as EnPostsSlugRouteImport } from './routes/_en/posts/$slug'
import { Route as ZhPostsIndexRouteImport } from './routes/zh/posts/index'
import { Route as ZhPostsSlugRouteImport } from './routes/zh/posts/$slug'
import { Route as ApiTtsLocaleSlugRouteImport } from './routes/api/tts/$locale/$slug'

const EnRouteRoute = EnRouteRouteImport.update({
  id: '/_en',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhRouteRoute = ZhRouteRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnChatRoute = EnChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPostsRouteRoute = EnPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnSearchRoute = EnSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => EnRouteRoute,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhAboutRoute = ZhAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhChatRoute = ZhChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhPostsRouteRoute = ZhPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhSearchRoute = ZhSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ZhRouteRoute,
} as any)
const EnPostsIndexRoute = EnPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnPostsRouteRoute,
} as any)
const EnPostsSlugRoute = EnPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnPostsRouteRoute,
} as any)
const ZhPostsIndexRoute = ZhPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhPostsRouteRoute,
} as any)
const ZhPostsSlugRoute = ZhPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ZhPostsRouteRoute,
} as any)
const ApiTtsLocaleSlugRoute = ApiTtsLocaleSlugRouteImport.update({
  id: '/api/tts/$locale/$slug',
  path: '/api/tts/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof EnIndexRoute
  '/zh': typeof ZhRouteRouteWithChildren
  '/posts': typeof EnPostsRouteRouteWithChildren
  '/zh/posts': typeof ZhPostsRouteRouteWithChildren
  '/about': typeof EnAboutRoute
  '/chat': typeof EnChatRoute
  '/search': typeof EnSearchRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/chat': typeof ZhChatRoute
  '/zh/search': typeof ZhSearchRoute
  '/zh/': typeof ZhIndexRoute
  '/posts/$slug': typeof EnPostsSlugRoute
  '/zh/posts/$slug': typeof ZhPostsSlugRoute
  '/posts/': typeof EnPostsIndexRoute
  '/zh/posts/': typeof ZhPostsIndexRoute
  '/api/tts/$locale/$slug': typeof ApiTtsLocaleSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof EnAboutRoute
  '/chat': typeof EnChatRoute
  '/search': typeof EnSearchRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/chat': typeof ZhChatRoute
  '/zh/search': typeof ZhSearchRoute
  '/': typeof EnIndexRoute
  '/zh': typeof ZhIndexRoute
  '/posts/$slug': typeof EnPostsSlugRoute
  '/zh/posts/$slug': typeof ZhPostsSlugRoute
  '/posts': typeof EnPostsIndexRoute
  '/zh/posts': typeof ZhPostsIndexRoute
  '/api/tts/$locale/$slug': typeof ApiTtsLocaleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_en': typeof EnRouteRouteWithChildren
  '/zh': typeof ZhRouteRouteWithChildren
  '/_en/posts': typeof EnPostsRouteRouteWithChildren
  '/zh/posts': typeof ZhPostsRouteRouteWithChildren
  '/_en/about': typeof EnAboutRoute
  '/_en/chat': typeof EnChatRoute
  '/_en/search': typeof EnSearchRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/chat': typeof ZhChatRoute
  '/zh/search': typeof ZhSearchRoute
  '/_en/': typeof EnIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/_en/posts/$slug': typeof EnPostsSlugRoute
  '/zh/posts/$slug': typeof ZhPostsSlugRoute
  '/_en/posts/': typeof EnPostsIndexRoute
  '/zh/posts/': typeof ZhPostsIndexRoute
  '/api/tts/$locale/$slug': typeof ApiTtsLocaleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/zh'
    | '/posts'
    | '/zh/posts'
    | '/about'
    | '/chat'
    | '/search'
    | '/zh/about'
    | '/zh/chat'
    | '/zh/search'
    | '/zh/'
    | '/posts/$slug'
    | '/zh/posts/$slug'
    | '/posts/'
    | '/zh/posts/'
    | '/api/tts/$locale/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/chat'
    | '/search'
    | '/zh/about'
    | '/zh/chat'
    | '/zh/search'
    | '/'
    | '/zh'
    | '/posts/$slug'
    | '/zh/posts/$slug'
    | '/posts'
    | '/zh/posts'
    | '/api/tts/$locale/$slug'
  id:
    | '__root__'
    | '/_en'
    | '/zh'
    | '/_en/posts'
    | '/zh/posts'
    | '/_en/about'
    | '/_en/chat'
    | '/_en/search'
    | '/zh/about'
    | '/zh/chat'
    | '/zh/search'
    | '/_en/'
    | '/zh/'
    | '/_en/posts/$slug'
    | '/zh/posts/$slug'
    | '/_en/posts/'
    | '/zh/posts/'
    | '/api/tts/$locale/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EnRouteRoute: typeof EnRouteRouteWithChildren
  ZhRouteRoute: typeof ZhRouteRouteWithChildren
  ApiTtsLocaleSlugRoute: typeof ApiTtsLocaleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_en': {
      id: '/_en'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_en/': {
      id: '/_en/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_en/about': {
      id: '/_en/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_en/chat': {
      id: '/_en/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof EnChatRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_en/posts': {
      id: '/_en/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof EnPostsRouteRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_en/search': {
      id: '/_en/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof EnSearchRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/zh/': {
      id: '/zh/'
      path: '/'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/zh/about': {
      id: '/zh/about'
      path: '/about'
      fullPath: '/zh/about'
      preLoaderRoute: typeof ZhAboutRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/zh/chat': {
      id: '/zh/chat'
      path: '/chat'
      fullPath: '/zh/chat'
      preLoaderRoute: typeof ZhChatRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/zh/posts': {
      id: '/zh/posts'
      path: '/posts'
      fullPath: '/zh/posts'
      preLoaderRoute: typeof ZhPostsRouteRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/zh/search': {
      id: '/zh/search'
      path: '/search'
      fullPath: '/zh/search'
      preLoaderRoute: typeof ZhSearchRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/_en/posts/': {
      id: '/_en/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof EnPostsIndexRouteImport
      parentRoute: typeof EnPostsRouteRoute
    }
    '/_en/posts/$slug': {
      id: '/_en/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof EnPostsSlugRouteImport
      parentRoute: typeof EnPostsRouteRoute
    }
    '/zh/posts/': {
      id: '/zh/posts/'
      path: '/'
      fullPath: '/zh/posts/'
      preLoaderRoute: typeof ZhPostsIndexRouteImport
      parentRoute: typeof ZhPostsRouteRoute
    }
    '/zh/posts/$slug': {
      id: '/zh/posts/$slug'
      path: '/$slug'
      fullPath: '/zh/posts/$slug'
      preLoaderRoute: typeof ZhPostsSlugRouteImport
      parentRoute: typeof ZhPostsRouteRoute
    }
    '/api/tts/$locale/$slug': {
      id: '/api/tts/$locale/$slug'
      path: '/api/tts/$locale/$slug'
      fullPath: '/api/tts/$locale/$slug'
      preLoaderRoute: typeof ApiTtsLocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnPostsRouteRouteChildren {
  EnPostsSlugRoute: typeof EnPostsSlugRoute
  EnPostsIndexRoute: typeof EnPostsIndexRoute
}

const EnPostsRouteRouteChildren: EnPostsRouteRouteChildren = {
  EnPostsSlugRoute: EnPostsSlugRoute,
  EnPostsIndexRoute: EnPostsIndexRoute,
}

const EnPostsRouteRouteWithChildren = EnPostsRouteRoute._addFileChildren(
  EnPostsRouteRouteChildren,
)

interface EnRouteRouteChildren {
  EnPostsRouteRoute: typeof EnPostsRouteRouteWithChildren
  EnAboutRoute: typeof EnAboutRoute
  EnChatRoute: typeof EnChatRoute
  EnSearchRoute: typeof EnSearchRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnPostsRouteRoute: EnPostsRouteRouteWithChildren,
  EnAboutRoute: EnAboutRoute,
  EnChatRoute: EnChatRoute,
  EnSearchRoute: EnSearchRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

interface ZhPostsRouteRouteChildren {
  ZhPostsSlugRoute: typeof ZhPostsSlugRoute
  ZhPostsIndexRoute: typeof ZhPostsIndexRoute
}

const ZhPostsRouteRouteChildren: ZhPostsRouteRouteChildren = {
  ZhPostsSlugRoute: ZhPostsSlugRoute,
  ZhPostsIndexRoute: ZhPostsIndexRoute,
}

const ZhPostsRouteRouteWithChildren = ZhPostsRouteRoute._addFileChildren(
  ZhPostsRouteRouteChildren,
)

interface ZhRouteRouteChildren {
  ZhPostsRouteRoute: typeof ZhPostsRouteRouteWithChildren
  ZhAboutRoute: typeof ZhAboutRoute
  ZhChatRoute: typeof ZhChatRoute
  ZhSearchRoute: typeof ZhSearchRoute
  ZhIndexRoute: typeof ZhIndexRoute
}

const ZhRouteRouteChildren: ZhRouteRouteChildren = {
  ZhPostsRouteRoute: ZhPostsRouteRouteWithChildren,
  ZhAboutRoute: ZhAboutRoute,
  ZhChatRoute: ZhChatRoute,
  ZhSearchRoute: ZhSearchRoute,
  ZhIndexRoute: ZhIndexRoute,
}

const ZhRouteRouteWithChildren =
  ZhRouteRoute._addFileChildren(ZhRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  EnRouteRoute: EnRouteRouteWithChildren,
  ZhRouteRoute: ZhRouteRouteWithChildren,
  ApiTtsLocaleSlugRoute: ApiTtsLocaleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
