/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZhRouteRouteImport } from './routes/_zh/route'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as ZhIndexRouteImport } from './routes/_zh/index'
import { Route as ZhAboutRouteImport } from './routes/_zh/about'
import { Route as ZhChatRouteImport } from './routes/_zh/chat'
import { Route as ZhPostsRouteRouteImport } from './routes/_zh/posts/route'
import { Route as ZhSearchRouteImport } from './routes/_zh/search'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnChatRouteImport } from './routes/en/chat'
import { Route as EnPostsRouteRouteImport } from './routes/en/posts/route'
import { Route as EnSearchRouteImport } from './routes/en/search'
import { Route as ZhPostsIndexRouteImport } from './routes/_zh/posts/index'
import { Route as ZhPostsSlugRouteImport } from './routes/_zh/posts/$slug'
import { Route as EnPostsIndexRouteImport } from './routes/en/posts/index'
import { Route as EnPostsSlugRouteImport } from './routes/en/posts/$slug'
import { Route as ApiTtsLocaleSlugRouteImport } from './routes/api/tts/$locale/$slug'

const ZhRouteRoute = ZhRouteRouteImport.update({
  id: '/_zh',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhAboutRoute = ZhAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhChatRoute = ZhChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhPostsRouteRoute = ZhPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ZhRouteRoute,
} as any)
const ZhSearchRoute = ZhSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ZhRouteRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnChatRoute = EnChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPostsRouteRoute = EnPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnSearchRoute = EnSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => EnRouteRoute,
} as any)
const ZhPostsIndexRoute = ZhPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhPostsRouteRoute,
} as any)
const ZhPostsSlugRoute = ZhPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ZhPostsRouteRoute,
} as any)
const EnPostsIndexRoute = EnPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnPostsRouteRoute,
} as any)
const EnPostsSlugRoute = EnPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnPostsRouteRoute,
} as any)
const ApiTtsLocaleSlugRoute = ApiTtsLocaleSlugRouteImport.update({
  id: '/api/tts/$locale/$slug',
  path: '/api/tts/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ZhIndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/posts': typeof ZhPostsRouteRouteWithChildren
  '/en/posts': typeof EnPostsRouteRouteWithChildren
  '/about': typeof ZhAboutRoute
  '/chat': typeof ZhChatRoute
  '/search': typeof ZhSearchRoute
  '/en/about': typeof EnAboutRoute
  '/en/chat': typeof EnChatRoute
  '/en/search': typeof EnSearchRoute
  '/en/': typeof EnIndexRoute
  '/posts/$slug': typeof ZhPostsSlugRoute
  '/en/posts/$slug': typeof EnPostsSlugRoute
  '/posts/': typeof ZhPostsIndexRoute
  '/en/posts/': typeof EnPostsIndexRoute
  '/api/tts/$locale/$slug': typeof ApiTtsLocaleSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof ZhAboutRoute
  '/chat': typeof ZhChatRoute
  '/search': typeof ZhSearchRoute
  '/en/about': typeof EnAboutRoute
  '/en/chat': typeof EnChatRoute
  '/en/search': typeof EnSearchRoute
  '/': typeof ZhIndexRoute
  '/en': typeof EnIndexRoute
  '/posts/$slug': typeof ZhPostsSlugRoute
  '/en/posts/$slug': typeof EnPostsSlugRoute
  '/posts': typeof ZhPostsIndexRoute
  '/en/posts': typeof EnPostsIndexRoute
  '/api/tts/$locale/$slug': typeof ApiTtsLocaleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_zh': typeof ZhRouteRouteWithChildren
  '/en': typeof EnRouteRouteWithChildren
  '/_zh/posts': typeof ZhPostsRouteRouteWithChildren
  '/en/posts': typeof EnPostsRouteRouteWithChildren
  '/_zh/about': typeof ZhAboutRoute
  '/_zh/chat': typeof ZhChatRoute
  '/_zh/search': typeof ZhSearchRoute
  '/en/about': typeof EnAboutRoute
  '/en/chat': typeof EnChatRoute
  '/en/search': typeof EnSearchRoute
  '/_zh/': typeof ZhIndexRoute
  '/en/': typeof EnIndexRoute
  '/_zh/posts/$slug': typeof ZhPostsSlugRoute
  '/en/posts/$slug': typeof EnPostsSlugRoute
  '/_zh/posts/': typeof ZhPostsIndexRoute
  '/en/posts/': typeof EnPostsIndexRoute
  '/api/tts/$locale/$slug': typeof ApiTtsLocaleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/posts'
    | '/en/posts'
    | '/about'
    | '/chat'
    | '/search'
    | '/en/about'
    | '/en/chat'
    | '/en/search'
    | '/en/'
    | '/posts/$slug'
    | '/en/posts/$slug'
    | '/posts/'
    | '/en/posts/'
    | '/api/tts/$locale/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/chat'
    | '/search'
    | '/en/about'
    | '/en/chat'
    | '/en/search'
    | '/'
    | '/en'
    | '/posts/$slug'
    | '/en/posts/$slug'
    | '/posts'
    | '/en/posts'
    | '/api/tts/$locale/$slug'
  id:
    | '__root__'
    | '/_zh'
    | '/en'
    | '/_zh/posts'
    | '/en/posts'
    | '/_zh/about'
    | '/_zh/chat'
    | '/_zh/search'
    | '/en/about'
    | '/en/chat'
    | '/en/search'
    | '/_zh/'
    | '/en/'
    | '/_zh/posts/$slug'
    | '/en/posts/$slug'
    | '/_zh/posts/'
    | '/en/posts/'
    | '/api/tts/$locale/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ZhRouteRoute: typeof ZhRouteRouteWithChildren
  EnRouteRoute: typeof EnRouteRouteWithChildren
  ApiTtsLocaleSlugRoute: typeof ApiTtsLocaleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_zh': {
      id: '/_zh'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ZhRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_zh/': {
      id: '/_zh/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/_zh/about': {
      id: '/_zh/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ZhAboutRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/_zh/chat': {
      id: '/_zh/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ZhChatRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/_zh/posts': {
      id: '/_zh/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof ZhPostsRouteRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/_zh/search': {
      id: '/_zh/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ZhSearchRouteImport
      parentRoute: typeof ZhRouteRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/chat': {
      id: '/en/chat'
      path: '/chat'
      fullPath: '/en/chat'
      preLoaderRoute: typeof EnChatRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/posts': {
      id: '/en/posts'
      path: '/posts'
      fullPath: '/en/posts'
      preLoaderRoute: typeof EnPostsRouteRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/search': {
      id: '/en/search'
      path: '/search'
      fullPath: '/en/search'
      preLoaderRoute: typeof EnSearchRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_zh/posts/': {
      id: '/_zh/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof ZhPostsIndexRouteImport
      parentRoute: typeof ZhPostsRouteRoute
    }
    '/_zh/posts/$slug': {
      id: '/_zh/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof ZhPostsSlugRouteImport
      parentRoute: typeof ZhPostsRouteRoute
    }
    '/en/posts/': {
      id: '/en/posts/'
      path: '/'
      fullPath: '/en/posts/'
      preLoaderRoute: typeof EnPostsIndexRouteImport
      parentRoute: typeof EnPostsRouteRoute
    }
    '/en/posts/$slug': {
      id: '/en/posts/$slug'
      path: '/$slug'
      fullPath: '/en/posts/$slug'
      preLoaderRoute: typeof EnPostsSlugRouteImport
      parentRoute: typeof EnPostsRouteRoute
    }
    '/api/tts/$locale/$slug': {
      id: '/api/tts/$locale/$slug'
      path: '/api/tts/$locale/$slug'
      fullPath: '/api/tts/$locale/$slug'
      preLoaderRoute: typeof ApiTtsLocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ZhPostsRouteRouteChildren {
  ZhPostsSlugRoute: typeof ZhPostsSlugRoute
  ZhPostsIndexRoute: typeof ZhPostsIndexRoute
}

const ZhPostsRouteRouteChildren: ZhPostsRouteRouteChildren = {
  ZhPostsSlugRoute: ZhPostsSlugRoute,
  ZhPostsIndexRoute: ZhPostsIndexRoute,
}

const ZhPostsRouteRouteWithChildren = ZhPostsRouteRoute._addFileChildren(ZhPostsRouteRouteChildren)

interface ZhRouteRouteChildren {
  ZhPostsRouteRoute: typeof ZhPostsRouteRouteWithChildren
  ZhAboutRoute: typeof ZhAboutRoute
  ZhChatRoute: typeof ZhChatRoute
  ZhSearchRoute: typeof ZhSearchRoute
  ZhIndexRoute: typeof ZhIndexRoute
}

const ZhRouteRouteChildren: ZhRouteRouteChildren = {
  ZhPostsRouteRoute: ZhPostsRouteRouteWithChildren,
  ZhAboutRoute: ZhAboutRoute,
  ZhChatRoute: ZhChatRoute,
  ZhSearchRoute: ZhSearchRoute,
  ZhIndexRoute: ZhIndexRoute,
}

const ZhRouteRouteWithChildren = ZhRouteRoute._addFileChildren(ZhRouteRouteChildren)

interface EnPostsRouteRouteChildren {
  EnPostsSlugRoute: typeof EnPostsSlugRoute
  EnPostsIndexRoute: typeof EnPostsIndexRoute
}

const EnPostsRouteRouteChildren: EnPostsRouteRouteChildren = {
  EnPostsSlugRoute: EnPostsSlugRoute,
  EnPostsIndexRoute: EnPostsIndexRoute,
}

const EnPostsRouteRouteWithChildren = EnPostsRouteRoute._addFileChildren(EnPostsRouteRouteChildren)

interface EnRouteRouteChildren {
  EnPostsRouteRoute: typeof EnPostsRouteRouteWithChildren
  EnAboutRoute: typeof EnAboutRoute
  EnChatRoute: typeof EnChatRoute
  EnSearchRoute: typeof EnSearchRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnPostsRouteRoute: EnPostsRouteRouteWithChildren,
  EnAboutRoute: EnAboutRoute,
  EnChatRoute: EnChatRoute,
  EnSearchRoute: EnSearchRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteRouteWithChildren = EnRouteRoute._addFileChildren(EnRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ZhRouteRoute: ZhRouteRouteWithChildren,
  EnRouteRoute: EnRouteRouteWithChildren,
  ApiTtsLocaleSlugRoute: ApiTtsLocaleSlugRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
